---

- name: Configurando IPV6
  hosts: csr1kv
  gather_facts: False
  connection: local

  tasks:
 
  - name: Agregar IPV6  a loopback 33
    ios_config:
      parents: "interface loopback 33"
      lines:
        - description IPv6 ADDRESS 
        - ipv6 address 2001:db8:acad:1::1/64
        - ipv6 address fe80::1:1 link-local
